/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Divider: typeof import('primevue/divider')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    PartyList: typeof import('./src/components/party-list/party-list.vue')['default']
    PartyMember: typeof import('./src/components/party-member/party-member.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadLogs: typeof import('./src/components/upload-logs/upload-logs.vue')['default']
  }
}
